const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const jsonPath = path.join(root, 'data.json');
const jsPath = path.join(root, 'data.js');

const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

const banner = [
  '// AUTOGENERATED from data.json em cada deploy.',
  '// Não edite este arquivo diretamente — ele é sobrescrito.',
  '// Pra mudar conteúdo: /admin/ (Decap CMS) ou edite data.json.',
  '',
].join('\n');

const out = banner + 'window.SURREAL = ' + JSON.stringify(data, null, 2) + ';\n';
fs.writeFileSync(jsPath, out, 'utf8');

console.log('✓ data.js regenerado (' + out.length + ' bytes, ' +
  data.menu.length + ' pratos, ' + data.bebidas.length + ' bebidas, ' +
  data.vinhos.length + ' vinhos)');
